/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_appsync_graphqlEndpoint": "https://kwmyoc7igzhc7hefse2blirmhy.appsync-api.us-east-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-uoccb4r5nzfxxlkdgqydf54a4e",
    "aws_cognito_identity_pool_id": "us-east-2:6f26dd4b-9c34-4ee6-9dd6-67289a672b6c",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_VAbLhySDs",
    "aws_user_pools_web_client_id": "6jiagmr17g1v5rdn4mu13shbhk",
    "oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ]
};


export default awsmobile;
